version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - mkdir -p app/python
      - pip install -r app/requirements.txt -t app/python/

  build:
    commands:
      - echo Zipping the layer...
      - cd app && zip -r layer.zip python/ && cd ..
      - echo Uploading ZIP to S3...
      - aws s3 cp app/layer.zip s3://$S3_BUCKET_NAME/layers/layer-$CODEBUILD_BUILD_NUMBER.zip
      - aws s3 cp app/layer.zip s3://$S3_BUCKET_NAME/layers/layer-latest.zip
      - echo Publishing Lambda Layer...
      - python app/publish_layer.py

  post_build:
    commands:
      - echo Done. Layer stored in S3 and published to Lambda.

artifacts:
  files:
    - app/layer.zip